### ISSUE TITLE
Add TravisCI integration.

### ISSUE THREAD

**Issue by am-kantox** [joshnuss/xml_builder#16]
Would you mind to add a [`TravisCI`](https://travis-ci.org/) integration?

It is as easy as follow the link, register there with your GH OAuth, and then put to the project root the file named `.travis.yml` having the following content:
```yml
language: elixir
elixir:
  - 1.3.4
after_script:
  - MIX_ENV=docs mix deps.get
  - MIX_ENV=docs mix inch.report
```

That way you’ll get all tests running for free on each subsequent pull request etc.

Unfortunately, I cannot do that for you since it establishes a link to the repo and since you are the maintainer...
